#!/bin/bash
# tjh
# Arch Linux Generate Order
# algo [device]


set -eu

device="$1"
host="$(cat /dev/urandom | tr -dc '[:alpha:]' | head -c 4)"
host="${host^^}"
rpart="root"
rpath="/dev/$host/$rpart"

rnew="$(mktemp -d)"
rlocal="/usr/local/bin/localinit"
echo "Device $device will be wiped you sure ? yes|(no)"

read response

if [ ! ${response^^} == "YES" ]
then
	echo "Device $device saved ! puh ..."
	exit 1
fi

wipefs $device

fdisk $device << EOF
g
n


+1G
Y
n



Y
a
1
w
q
EOF

pool ${device}2 into $host
pool $rpart from $host 7G

mkfs.fat -F 32 ${device}1
mkfs.btrfs -f -m dup -d single $rpath

mkdir -p $rnew
mount $rpath $rnew
mount $rpath/boot ${device}1

pacstrap $rnew base base-devel linux linux-firmware man-db man-pages texinfo lvm2 btrfs-progs grub efibootmgr vim git

genfstab -U $rnew >> $rnew/etc/fstab

cat > $rnew$rlocal <<  EOF
#!/bin/bash
# tjh
# bin/localinit

ln -sf /usr/share/zoneinfo/Europa/Berlin /etc/localtime
hwclock --systohc

cat >> /etc/locale.gen << EOL
en_US.UTF-8 UTF-8
de_DE.UTF-8 UTF-8
EOL

locale-gen

cat > /etc/locale.conf << EOL
LANG=en_US.UTF-8
EOL

cat > /etc/vconsole.conf << EOL
KEYMAP=de
EOL

cat > /etc/hostname << EOL
${host}
EOL

mkinitcpio -P
exit

EOF

arch-chroot $rnew $rlocal

exit
