#!/bin/bash
# jon 2020
# bin/dl-stages


target=$1
architecture=amd64
diff=hardened

# Downloading Tarball
wget -r -np -nH --cut-dirs=7 -P $target -A stage3-$architecture-$diff-[0-9]*T[0-9]*Z.tar.xz* https://ftp-stud.hs-esslingen.de/pub/Mirrors/gentoo/releases/$architecture/autobuilds/current-stage3-$architecture-$diff/


# Downloading Keys
wget -O- https://gentoo.org/.well-known/openpgpkey/hu/wtktzo4gyuhzu8a4z5fdj3fgmr1u6tob?l=releng | gpg --import


gpg --verify $target/stage3*.tar.*.DIGESTS.asc
grep -A 1 -i sha512 $target/stage3*tar.*.DIGESTS.asc
sha512sum $target/stage3*.tar.*

echo "[USER] Everything checks out? y|[n]"
read response

if [ -z $response ]
then 
	response=n
fi

if [ ! $response = "y" ]
then
	echo "[$0] Adding dirty flag"
	touch $target/.dirty
	echo "[$0] Stopping installation got wrong response"
	exit 1
fi

