#!/bin/bash
# tjh
# Fenster
# f

# Start inside Gentoo Enviroment

# After Configs -> # SCRIPT

source /etc/profile

msg () {
	echo "[$0] $1"
}
error () {

	2>&1 msg "(E) $1"
	exit 1
}

cat > /etc/portage/packages << EOF
sys-kernel/vanilla-sources
sys-kernel/gentoo-sources
sys-kernel/genkernel
sys-kernel/linux-firmware

sys-boot/grub
sys-boot/efibootmgr

sys-fs/btrfs-progs
sys-fs/ntfs3g
sys-fs/dosfstools
sys-fs/e2fsprogs
sys-fs/xfsprogs

app-shells/bash
app-shells/loksh
dev-lang/tcc
dev-lang/ruby
dev-lang/rust
dev-lang/python
dev-lang/go
app-editors/vim
app-editors/emacs
app-text/texlive

sys-apps/man-db
sys-apps/man-pages
sys-apps/man-pages-posix
sys-power/acpi
app-portage/layman
app-eselect/eselect-repository
app-portage/eix
app-portage/gentoolkit
app-portage/cpuid2cpuflags
app-portage/repoman
app-admin/metalog
app-admin/doas
sys-process/cronie
sys-fs/cryptsetup

net-wireless/wpa_supplicant
net-wireless/bluez

net-misc/openssh
net-misc/dhcpcd
net-vpn/openvpn
net-vpn/6tunnel
net-vpn/tor
net-firewall/ufw

net-p2p/transmission
net-p2p/mktorrent
net-p2p/torrentinfo
net-p2p/bitcoind
net-p2p/bitcoin-cli
net-p2p/freenet
net-p2p/go-ipfs
net-ftp/ftp
net-misc/wget
net-misc/curl
www-servers/thttpd
www-client/lynx
dev-vcs/git

media-sound/pulseaudio
media-sound/cmus
media-video/ffmpeg
app-misc/figlet
net-print/cups
media-gfx/qrencode
app-accessibility/espeak

app-crypt/chntpw
app-crypt/aespipe
app-crypt/aescrypt
app-crypt/argon2
app-crypt/certbot
app-crypt/easy-rsa
app-crypt/hashcat
net-analyzer/nmap
net-analyzer/zmap
net-analyzer/macchanger
net-analyzer/dhcpdump
net-analyzer/dhcp_probe
net-analyzer/arp-scan
net-analyzer/arpoison
net-analyzer/dnstracer
net-analyzer/openbsd-netcat
net-analyzer/traceroute
net-analyzer/scanlogd
net-analyzer/scanssh
net-analyzer/xprobe
net-analyzer/zniper

x11-base/xorg-x11
x11-apps/xinit
x11-wm/awesome
media-fonts/terminus-font
x11-misc/xclip
x11-misc/arandr
x11-misc/dmenu
x11-misc/polybar
x11-misc/redshift
x11-terms/rxvt-unicode

app-emulation/qemu
app-emulation/wine-vanilla

media-gfx/feh
net-misc/youtube-dl
www-client/surf
net-p2p/transmission-remote-gtk
net-p2p/bitcoin-qt

x11-terms/rxvt-unicode
app-editors/hexedit
www-client/firefox
www-client/chromium
net-im/telegram-desktop
net-im/signal-desktop-bin
mail-client/thunderbird
app-office/libreoffice
net-analyzer/wireshark
net-analyzer/ettercap
media-sound/audacity
media-sound/mixxx
media-sound/ardour
media-libs/gstreamer
media-video/mpv
media-video/vlc
media-gfx/blender
media-gfx/gimp
media-gfx/inkscape
media-video/obs-studio
net-wireless/gnuradio
dev-util/android-studio
app-editors/vscode

sci-electronics/kicad
sci-electronics/kicad-templates
sci-electronics/kicad-footprints
sci-electronics/kicad-symbols
EOF

cat > /etc/portage/make.conf << EOF
# Generated by gg

COMMON_FLAGS="-O2 -pipe -march=x86-64"
CFLAGS="\${COMMON_FLAGS}"
CXXFLAGS="\${COMMON_FLAGS}"
FCFLAGS="\${COMMON_FLAGS}"
FFLAGS="\${COMMON_FLAGS}"

MAKEOPTS="-j4"

GRUB_PLATFORMS="efi-32 efi-64 pc"
FEATURES="buildpkg"

PORTDIR="/var/db/repos/gentoo"
DISTDIR="/var/cache/distfiles"
PKGDIR="/var/cache/binpkgs"

LC_MESSAGES=C
EOF

cat > /etc/portage/package.use/default << EOF
*/* -bindist hardened X man vim-syntax dbus pulseaudio bluetooth xinerama curl emacs gimp gstreamer libmpv gif flac mp3 mp4 ogg acc png jpeg svg rar lzma lz4 lzo xz zip zlib zstd raw python ruby smp unicode usb xcb zsh-completion qrcode
app-admin/sudo offensive
app-arch/libarchive -lz4

EOF
cat > /etc/portage/package.license << EOF
sys-kernel/linux-firmware linux-fw-redistributable no-source-code
EOF
cat > /etc/portage/package.accept_keywords/default << EOF
*/* ~amd64
EOF

msg "Checking System Requirements"
/bin/bash

# SCRIPT

msg "System syncing"

source /etc/profile
emerge-webrsync

msg "Configuring unspecific Settings"

echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen
echo "de_DE.UTF-8 UTF-8" >> /etc/locale.gen
echo "Europe/Berlin" > /etc/timezone
locale-gen
eselect locale set de_DE.utf8
rm /etc/localtime
emerge --config sys-libs/timezone-data

env-update 
source /etc/profile

msg "Installing Packages"
bin/bash

#emerge -k --usepkg y --verbose --update --deep --newuse @world
#emerge @preserved-rebuild
#emerge -k --usepkg y --verbose $(cat /etc/portage/packages | tr "\n" " " )

#msg "Building Kernel"

#genkernel all

#passwd
