#!/bin/bash
# jon 2021
# bin/mksdev
# Make Secure Device

# mksdev [dev0]
# mksdev [dev0] [dev1]

set -e

if [ -e $1 ]
then
	device0="$1"
else
	dev_start="/dev/" # TODO Implement local dir 
	device0="$dev_start$1"
	if [ ! -e "$device0" ]
	then
		2>&1 echo "[$(basename $0)] -2 No valid Device"
		exit -2
	fi

fi


num0=0
# autofind free devnode
while [[ -e "/dev/mapper/sdev$num0" ]]
do
	num0+=1
done

crypt_dev0="/dev/mapper/sdev$num0"

fs=btrfs
fs_opt=""

echo "[$(basename $0)] Password for the Secure Device >"
read -s password

echo "[$(basename $0)] Setup $device0 as $crypt_dev0"
echo "$password" | cryptsetup luksFormat $device0
echo "$password" | cryptsetup luksOpen $device0 sdev$num0

if [ -e $2 ]
then
	device1="$dev_start$2"
	fs_raid="raid1"

	num1=$num0 
	# autofind free devnode
	while [[ -e "/dev/mapper/smdev$num1" ]]
	do
		num1+=1
	done
	
	crypt_dev1="/dev/mapper/smdev$num1"

	echo "[$(basename $0)] Setup $device1 as $crypt_dev1"
	rev "$password" | cryptsetup luksFormat $device1
	rev "$password" | cryptsetup luksOpen $device1 smdev$num1

else
	fs_raid="dup"
fi

mkfs.$fs $fs_opt -m $fs_raid -d $fs_raid $crypt_dev0 $crypt_dev1

sync

if [ ! "" == "$crypt_dev1" ]
then
	cryptsetup luksClose $crypt_dev1
fi
cryptsetup luksClose $crypt_dev0

