#!/bin/bash
# tjh
# bin/mksdev
# Make Secure Device

# mksdev [dev0]
# mksdev [dev0] [dev1]
# mksdev -h [header0] [dev0]
# mksdev -h [header0] [dev0] [header1] [dev1]

set -e

if [ "$1" == "-h" ]
then
	fs_opt="-h"
	header0="$2"
	shift
	shift
fi

if [ -e $1 ]
then
	device0="$1"
else
	dev_start="/dev/" # TODO Implement local dir 
	device0="$dev_start$1"
	if [ ! -e "$device0" ]
	then
		2>&1 echo "[$(basename $0)] -2 No valid Device"
		exit -2
	fi

fi


num0=0
# autofind free devnode
while [[ -e "/dev/mapper/sdev$num0" ]]
do
	num0+=1
done

crypt_dev0="/dev/mapper/sdev$num0"

fs=btrfs


echo "[$(basename $0)] Password for the Secure Device >"
read -s password

echo "[$(basename $0)] Setup $device0 as $crypt_dev0"
echo "$password" | cryptsetup $fs_opt $header0 luksFormat $device0
echo "$password" | cryptsetup open $device0 $(basename $crypt_dev0)

if [ "$fs_opt" == "-h" ]
then 
	header1=$2
	shift
fi

if [ ! -e "$dev_start$2"  ]
then
	fs_raid="dup"
else
	fs_raid="raid1"
	device1="$dev_start$2"

	num1=$num0 
	# autofind free devnode
	while [[ -e "/dev/mapper/smdev$num1" ]]
	do
		num1+=1
	done
	
	crypt_dev1="/dev/mapper/smdev$num1"

	echo "[$(basename $0)] Setup $device1 as $crypt_dev1"
	rev "$password" | cryptsetup $fs_opt $header1 luksFormat $device1
	rev "$password" | cryptsetup open $device1 $(basename $crypt_dev1)

fi

mkfs.$fs $fs_opt -m $fs_raid -d $fs_raid $crypt_dev0 $crypt_dev1


echo "[$(basename $0)] Close Cryptsetup ? [Enter]"
read response

sync

cryptsetup close $crypt_dev0

if [ -e $device1 ]
then
	cryptsetup close $crypt_dev1
fi
