#!/bin/bash
# jon 2021
# bin/mksmdev
# Make Secure Mirrored Device

#set -eu

device0=$1

if [ ! "" == $2 ]
then
	device1=$2
fi

num0=0
num1=1

fs=btrfs
fs_opt="-m raid1 -d "
fs_opt="-m raid1 -d raid1"

echo "[mksmdev] Password for the Secure Mirrored Device >"
read -s password

# Device 1
while [[ -e "/dev/mapper/smdev$num0" ]]
do
	num0+=1
done

echo "[mksmdev] Setup $device0 as smdev$num0"
echo "$password" | cryptsetup luksFormat $device0
echo "$password" | cryptsetup luksOpen $device0 smdev$num0

# Device 2
while [[ -e "/dev/mapper/smdev$num1" ]]
do
	num1+=1
done

echo "[mksmdev] Setup $device1 as smdev$num1"
rev "$password" | cryptsetup luksFormat $device1
rev "$password" | cryptsetup luksOpen $device1 smdev$num1


mkfs.$fs $fs_opt /dev/mapper/smdev$num0 /dev/mapper/smdev$num1

cryptsetup luksClose smdev$num0
cryptsetup luksClose smdev$num1

