#!/bin/bash
# jon 2021
# bin/mksmdev
# Make Secure Mirrored Device

set -eu

device0=$1
device1=$2

num0=0
num1=0

fs=btrfs
fs_opt="-m raid1 -d raid1"

echo "[mksmdev] Password for the Secure Mirrored Device >"
read -s password

# Device 1
while [[ ! -e "/dev/mapper/smdev$num0" && $num0 -le 256 ]]
do
	num0+=1
done

echo $password | cryptsetup luksFormat $device0
cryptsetup luksOpen $device0 sdev$num0

# Device 2
while [[ ! -e "/dev/mapper/smdev$num1" && $num1 -le 256 ]]
do
	num1+=1
done

rev $password | cryptsetup luksFormat $device1
cryptsetup luksOpen $device1 sdev$num1


mkfs.$fs $fs_opt /dev/mapper/sdev$num0 /dev/mapper/sdev$num1

cryptsetup luksClose sdev$num

