#!/bin/bash 
# jon 2021
# bin/nroot

set -eu

if [ -z $1 ]
then
	2>&1 echo "$0: No Target"
	exit 1
fi

$target=$1

echo "[$0] Setting up (<net|proc|sys|dev>)"

cp --dereference /etc/resolv.conf $target/etc/resolv.conf

mount --types proc /proc $target/proc
mount --rbind /sys $target/sys
mount --make-rslave $target/sys
mount --rbind /dev $target/dev
mount --make-rslave $target/dev 

chroot $target /bin/bash

echo "[$0] Cleanup ? <n|(y)>"

read response
if [ -z $response ]
then
	umount -l $target/dev{/shm,/pts,}
	umount -R $target{/proc,/sys}
fi
