#!/bin/bash
# jon 2021
# bin/pkg

#set -e

pkg=$1

pkgmgr="portage"
defaults="--autounmask"
pkg_install="emerge"

$pkg_install --pretend $defaults $pkg 

echo "$0: Emerge Package ($pkg) ?"
read $response

if [ $response == ]
then
	echo "$0: Not emerging ($pkg)_$response_"
	exit 1
else
	$pkg_install $defaults $pkg &
	tail -f /var/log/emerge.log
fi
