#!/bin/bash
# tjh
# bin/pool
# Pooling Disk Resources

set -u

usage() {
	1>&2 echo "[$0] pool [device] into [poolname]"
	1>&2 echo "[$0] pool [device] from [poolname] [size]"
	exit 1
}



if [ "$2" == "into" ]
then
	pvcreate $1
	if ! vgcreate $3 $1 2> /dev/null 
	then
		vgextend $3 $1
	fi

elif [ "$2" == "from" ]
then
	lvcreate -L $4 -n $1 $3
else
	usage	
fi

exit 0
