#!/bin/bash
# jon 2021
# bin/smnt
# Make Secure Mirrored Device

# smnt [mount point] [dev0]
# smnt [mount point] [dev0] [dev1]

set -e

mntpnt=$1

if [ -e ""]
device0=$2
device1=$3


num0=0
# autofind free devnode
while [[ -e "/dev/mapper/smdev$num0" ]]
do
	num0+=1
done
num1=1
# autofind free devnode
while [[ -e "/dev/mapper/smdev$num1" ]]
do
	num1+=1
done

fs=btrfs

echo "[$(basename $0)] Password for the Secure Device >"
read -s password


echo "[$(basename $0)] Setup $device0 as smdev$num0"
echo "$password" | cryptsetup luksOpen $device0 smdev$num0


echo "[$(basename $0)] Setup $device1 as smdev$num1"
rev "$password" | cryptsetup luksOpen $device1 smdev$num1

mount -t $fs /dev/mapper/smdev$num0 $mntpnt 

echo "[$(basename $0)] Unmounting on Enter"
read response

cryptsetup luksClose smdev$num0
cryptsetup luksClose smdev$num1

