#!/bin/bash
# jon 2021
# bin/smnt
# Make Secure Mirrored Device

# smnt [dev0] [dev1] [mount point]

#set -eu

device0=$1
device1=$2

mntpnt=$3

num0=0
num1=1

fs=btrfs

echo "[$0] Password for the Secure Mirrored Device >"
read -s password

# Device 1
while [[ -e "/dev/mapper/smdev$num0" ]]
do
	num0+=1
done

echo "[$0] Setup $device0 as smdev$num0"
echo "$password" | cryptsetup luksOpen $device0 smdev$num0

# Device 2
while [[ -e "/dev/mapper/smdev$num1" ]]
do
	num1+=1
done

echo "[$0] Setup $device1 as smdev$num1"
rev "$password" | cryptsetup luksOpen $device1 smdev$num1

mount -t $fs /dev/mapper/smdev$num0 $mntpnt 

echo "Unmount ? [y]"
read response

cryptsetup luksClose smdev$num0
cryptsetup luksClose smdev$num1

