#!/usr/bin/env bash
if [[-e /var/cache/eix/portage.eix ]]; then
	cp -a /var/cache/eix/portage.eix /var/cache/eix/previous.eix;
	cp -a /var/cache/eix/portage.eix /var/cache/eix/portage.$(date "+%d-%m-%y").eix;
fi
eix-update
if [[-e /var/cache/eix/previous.eix ]]; then
	eix-diff;
fi

